# Generated by Django 3.2 on 2022-08-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
