# Generated by Django 3.2 on 2022-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='update_date',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата запроса к геокодеру'),
        ),
    ]
