version: '3.7'
services:
  db:
    image: postgres:12.9
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env.db


  django:
    build: .
    command: python  /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - ./star_burger/.env

  node:
    build: ./bundles-src
    # порты
    ports:
      - 3000:3000
    volumes:
      - ./bundles-src/:/usr/src/app/bundles-src/
    command: npm run
    depends_on:
      - django

volumes:
  postgres_data:

