version: '3.7'
services:
  db:
    image: postgres:12.9
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=star_burger
      - POSTGRES_USER=devman
      - POSTGRES_PASSWORD=devman
      - POSTGRES_PORT=5432

  web:
    build: .
    command: python  /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./star_burger/.env
volumes:
  postgres_data:

