# Generated by Django 3.2 on 2022-05-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20220503_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
