# Generated by Django 3.2 on 2022-05-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'НЕ ОБРАБОТАН'), ('DONE', 'ВЫПОЛНЕН')], db_index=True, default='UNPROCESSED', max_length=20, verbose_name='Статус Заказа'),
        ),
    ]
