# Generated by Django 3.2 on 2022-05-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20220506_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'НАЛИЧНЫЕ'), ('ONLINE', 'ОНЛАЙН')], db_index=True, default='ONLINE', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
