# Generated by Django 3.2 on 2022-05-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Не обработан'), ('DONE', 'Выполнен')], db_index=True, default='UNPROCESSED', max_length=20, verbose_name='Статус Заказа'),
        ),
    ]
