# Generated by Django 3.2 on 2022-05-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Наличные'), ('Online', 'Онлайн')], db_index=True, default='ONLINE', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Не обработан'), ('Done', 'Выполнен')], db_index=True, default='Unprocessed', max_length=20, verbose_name='Статус Заказа'),
        ),
    ]
