# Generated by Django 3.2 on 2022-05-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20220520_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Наличные'), ('Online', 'Онлайн')], db_index=True, default='Online', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
