# Generated by Django 3.2 on 2022-05-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('ONLINE', 'Онлайн')], db_index=True, default='ONLINE', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Не обработан'), ('DONE', 'Выполнен')], db_index=True, default='UNPROCESSED', max_length=20, verbose_name='Статус Заказа'),
        ),
    ]
