# Generated by Django 3.2 on 2022-05-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_order_cooked_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cooked_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='foodcartapp.restaurant', verbose_name='Готовящий ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Не обработан'), ('PROCESSED', 'Готовится'), ('DONE', 'Выполнен')], db_index=True, default='UNPROCESSED', max_length=20, verbose_name='Статус Заказа'),
        ),
    ]
